// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjDOAam8NTkBr6qsFBedfXdULbW4U3l6k',
    appId: '1:17603188777:web:9d4b2c2da82a2a40246438',
    messagingSenderId: '17603188777',
    projectId: 'learningdart-571ac',
    authDomain: 'learningdart-571ac.firebaseapp.com',
    storageBucket: 'learningdart-571ac.appspot.com',
    measurementId: 'G-S8GMS2EDH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJr_I7ytn8vLxIogO9T4yKCY6vDURNtoU',
    appId: '1:17603188777:android:59e135d9a6c8b520246438',
    messagingSenderId: '17603188777',
    projectId: 'learningdart-571ac',
    storageBucket: 'learningdart-571ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuBG6YKFJ9Uq8ruqUyJ1f129vLul1VKR4',
    appId: '1:17603188777:ios:e0032661126da217246438',
    messagingSenderId: '17603188777',
    projectId: 'learningdart-571ac',
    storageBucket: 'learningdart-571ac.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuBG6YKFJ9Uq8ruqUyJ1f129vLul1VKR4',
    appId: '1:17603188777:ios:1bdb86c37ec06ad3246438',
    messagingSenderId: '17603188777',
    projectId: 'learningdart-571ac',
    storageBucket: 'learningdart-571ac.appspot.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
